--COUNT(*),COUNT(限定欄位),COUNT(1) 差別是什麼要查

--1. 注意大小寫,統一格式, JOIN=INNER JOIN
SELECT blr.KEEPER_ID AS KeeperId, mm.USER_CNAME AS CName, mm.USER_ENAME AS EName, 
	   YEAR(blr.LEND_DATE) AS BorrowYear, COUNT(book_id) AS BorrowCnt
FROM BOOK_LEND_RECORD blr
JOIN MEMBER_M mm
	ON(blr.CRE_USR=mm.USER_ID) 
GROUP BY blr.KEEPER_ID, mm.USER_CNAME,mm.USER_ENAME,YEAR(blr.LEND_DATE)
ORDER BY blr.KEEPER_ID , YEAR(blr.LEND_DATE);

--2. 數字重複的問題(排名陷阱) ,要問對方
SELECT * FROM BOOK_LEND_RECORD blr;
SELECT * FROM MEMBER_M;
SELECT * FROM BOOK_DATA;
SELECT * FROM SPAN_TABLE;

--第一種模式 沒有重複的
SELECT TOP 5 blr.BOOK_ID, bd.BOOK_NAME, COUNT(blr.BOOK_ID) AS QTY
FROM dbo.BOOK_LEND_RECORD blr 
JOIN BOOK_DATA bd 
    ON blr.BOOK_ID=bd.BOOK_ID
GROUP BY blr.BOOK_ID,bd.BOOK_NAME
ORDER BY COUNT(blr.BOOK_ID) DESC;

--第二種模式 有重複的
SELECT TOP 5 WITH TIES blr.BOOK_ID, bd.BOOK_NAME, COUNT(blr.BOOK_ID) AS QTY
FROM dbo.BOOK_LEND_RECORD blr 
JOIN BOOK_DATA bd 
    ON blr.BOOK_ID=bd.BOOK_ID
GROUP BY blr.BOOK_ID,bd.BOOK_NAME
ORDER BY COUNT(blr.BOOK_ID) DESC;

--3. 
SELECT CASE (MONTH(LEND_DATE)/4)+1
       WHEN 1 THEN '2019/01~2019/03'
       WHEN 2 THEN '2019/04~2019/06'
       WHEN 3 THEN '2019/07~2019/09'
       WHEN 4 THEN '2019/10~2019/12'
       END AS QUARTERS, 
	   COUNT(LEND_DATE) AS Cnt
FROM BOOK_LEND_RECORD 
WHERE YEAR(LEND_DATE)='2019' 
GROUP BY (MONTH(LEND_DATE)/4)+1;

--4. 注意數字重複的問題(排名陷阱)
SELECT * FROM BOOK_CLASS;
SELECT * FROM BOOK_DATA WHERE BOOK_NAME='信用風險議題與資訊平台規劃#2';
SELECT * FROM BOOK_LEND_RECORD WHERE BOOK_ID=441;

--先把要得變成subquery後就可以把使用想要的欄位的別名
SELECT sub.seq,sub.BookClass,sub.BookId,sub.BookName,sub.Cnt
FROM (SELECT ROW_NUMBER() OVER(PARTITION BY bc.BOOK_CLASS_NAME ORDER BY COUNT(blr.BOOK_ID) DESC) AS seq, 
       bc.BOOK_CLASS_NAME AS BookClass,bd.BOOK_ID AS BookId , bd.BOOK_NAME AS BookName, COUNT(blr.BOOK_ID) AS Cnt
FROM BOOK_CLASS bc 
JOIN BOOK_DATA bd 
    ON bc.BOOK_CLASS_ID=bd.BOOK_CLASS_ID 
JOIN BOOK_LEND_RECORD blr 
    ON BD.BOOK_ID = blr.BOOK_ID
GROUP BY bd.BOOK_ID,bd.BOOK_NAME,bc.BOOK_CLASS_NAME) AS sub
WHERE sub.seq <= 3

SELECT * FROM BOOK_CLASS;
SELECT * FROM BOOK_DATA WHERE BOOK_CLASS_ID='CCS';
SELECT * FROM BOOK_LEND_RECORD WHERE BOOK_ID=1839;

--5. NOT YET CCS那行為什麼跑的年份跟題目的答案不一樣 有問題繼續研究
/*SELECT bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,COUNT(blr.BOOK_ID),YEAR(blr.LEND_DATE)
FROM BOOK_LEND_RECORD blr 
JOIN BOOK_DATA bd
ON blr.BOOK_ID = bd.BOOK_ID
JOIN BOOK_CLASS bc
ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
GROUP BY YEAR(LEND_DATE),bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME;
*/

SELECT sub.ClassId,sub.ClassName,sub.CNT2016,sub.CNT2017,sub.CNT2018,sub.CNT2019
FROM (SELECT ROW_NUMBER() OVER(PARTITION BY bc.BOOK_CLASS_NAME ORDER BY YEAR(blr.LEND_DATE)) AS seq,
      bc.BOOK_CLASS_ID AS ClassId, bc.BOOK_CLASS_NAME AS ClassName, 
      COUNT(blr.BOOK_ID) AS CNT2016 
/*      LEAD(COUNT(blr.BOOK_ID),1,0) OVER(PARTITION BY bc.BOOK_CLASS_ID ORDER BY YEAR(blr.LEND_DATE)) AS CNT2017, 
      LEAD(COUNT(blr.BOOK_ID),2,0) OVER(PARTITION BY bc.BOOK_CLASS_ID ORDER BY YEAR(blr.LEND_DATE)) AS CNT2018,
      LEAD(COUNT(blr.BOOK_ID),3,0) OVER(PARTITION BY bc.BOOK_CLASS_ID ORDER BY YEAR(blr.LEND_DATE)) AS CNT2019
*/
      FROM BOOK_CLASS bc 
      JOIN BOOK_DATA bd
          ON bc.BOOK_CLASS_ID=bd.BOOK_CLASS_ID 
      JOIN BOOK_LEND_RECORD blr 
          ON bd.BOOK_ID = blr.BOOK_ID
--		  WHERE YEAR(blr.LEND_DATE)
GROUP BY bc.BOOK_CLASS_ID, bc.BOOK_CLASS_NAME, YEAR(blr.LEND_DATE)) AS sub
WHERE sub.seq <= 1;

--6.
SELECT * FROM BOOK_CLASS;
SELECT * FROM BOOK_DATA;
SELECT * FROM BOOK_LEND_RECORD;

SELECT ClassId, ClassName,  ISNULL([2016],0) AS CNT2016, ISNULL([2017],0) AS CNT2017,
       ISNULL([2018],0) AS CNT2018, ISNULL([2019],0) AS CNT2019
FROM (
      SELECT bc.BOOK_CLASS_ID AS ClassId, bc.BOOK_CLASS_NAME AS ClassName, 
			COUNT(blr.BOOK_ID) AS Cnt, YEAR(blr.LEND_DATE) AS Orderyear
      FROM BOOK_CLASS bc
      JOIN BOOK_DATA bd
	     ON bc.BOOK_CLASS_ID = bd.BOOK_CLASS_ID
	  JOIN BOOK_LEND_RECORD blr
	     ON bd.BOOK_ID = blr.BOOK_ID
	  GROUP BY bc.BOOK_CLASS_ID,bc.BOOK_CLASS_NAME,YEAR(blr.LEND_DATE)
	  ) AS sub
PIVOT(SUM(Cnt) FOR Orderyear
      IN ([2016],[2017],[2018],[2019]))	AS pvt
ORDER BY pvt.ClassId;

--7.
SELECT * FROM BOOK_LEND_RECORD;
SELECT * FROM MEMBER_M;
SELECT * FROM BOOK_DATA;
SELECT * FROM BOOK_CODE;
SELECT * FROM BOOK_CLASS;
SELECT CONCAT(YEAR(bd.BOOK_BOUGHT_DATE),'/',MONTH(bd.BOOK_BOUGHT_DATE),'/',FORMAT(bd.BOOK_BOUGHT_DATE,'%d')) AS DATE
FROM BOOK_DATA bd;

SELECT bd.BOOK_ID AS 書本ID, 
      CONCAT(YEAR(bd.BOOK_BOUGHT_DATE),'/',MONTH(bd.BOOK_BOUGHT_DATE),'/',FORMAT(bd.BOOK_BOUGHT_DATE,'%d')) AS 購書日期,
      CONCAT(YEAR(blr.LEND_DATE),'/',MONTH(blr.LEND_DATE),'/',FORMAT(blr.LEND_DATE,'%d')) AS 借閱日期, 
      CONCAT(bd.BOOK_CLASS_ID,'-',bc.BOOK_CLASS_NAME) AS 書籍類別,
      CONCAT(blr.KEEPER_ID,'-',mm.USER_CNAME,'(',mm.USER_ENAME,')') AS 借閱人,
      CONCAT(bco.CODE_ID ,'-',bco.CODE_NAME) AS 狀態,
      CONCAT(bd.BOOK_AMOUNT,'元') AS 購書金額
FROM BOOK_CLASS bc 
JOIN BOOK_DATA bd 
    ON bc.BOOK_CLASS_ID=bd.BOOK_CLASS_ID 
JOIN BOOK_LEND_RECORD blr 
    ON BD.BOOK_ID = blr.BOOK_ID 
JOIN MEMBER_M mm 
    ON blr.KEEPER_ID=mm.USER_ID
JOIN BOOK_CODE bco 
    ON bd.BOOK_STATUS= bco.CODE_ID --CODE_TYPE='BOOK_STATUS'
WHERE mm.USER_ID='0002' AND bco.CODE_TYPE='BOOK_STATUS'
ORDER BY bd.BOOK_AMOUNT DESC;

--8.
SELECT * FROM BOOK_LEND_RECORD WHERE BOOK_ID=2004;
SELECT * FROM BOOK_DATA WHERE BOOK_ID=2004;
SELECT * FROM MEMBER_M;
SELECT * FROM BOOK_CODE;
SELECT * FROM BOOK_CLASS;

INSERT INTO BOOK_LEND_RECORD (BOOK_ID,KEEPER_ID,LEND_DATE) VALUES (2004,'0002',CONVERT(DATE,GETDATE()));
UPDATE BOOK_DATA SET BOOK_KEEPER='0002' WHERE BOOK_ID=2004;
UPDATE BOOK_LEND_RECORD SET LEND_DATE='2019/01/02' WHERE KEEPER_ID='0002';


--9.
DELETE FROM BOOK_LEND_RECORD
WHERE BOOK_ID=2004 AND KEEPER_ID='0002'; 
